=== alimdul/XMLWebParsing/target/classes/data/minerals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/minerals"
        xmlns:tns="http://www.example.com/minerals"
        elementFormDefault="qualified">

    <element name="minerals">
        <complexType>
            <sequence>
                <element ref="tns:mineral"
                         minOccurs="16"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <element name="mineral" type="tns:Mineral" abstract="true"/>
    <element name="precious-stone" type="tns:Precious-stone" substitutionGroup="tns:mineral"/>
    <element name="semiprecious-stone" type="tns:Semiprecious-stone" substitutionGroup="tns:mineral"/>

    <complexType name="Mineral">
        <sequence>
            <element name="color" type="tns:Color"/>
            <element name="transparence" type="tns:Transparence"/>
            <element name="value" type="tns:Value"/>
            <element name="edges-number" type="tns:Edges-number"/>
        </sequence>
        <attribute name="minerals-id" type="tns:Minerals-id" use="required"/>
    </complexType>

    <complexType name="Precious-stone">
        <complexContent>
            <extension base="tns:Mineral">
                <attribute name="name" type="tns:Name" use="required"/>
                <attribute name="origin" type="tns:Origin" use="optional"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Semiprecious-stone">
        <complexContent>
            <extension base="tns:Mineral">
                <attribute name="name" type="tns:Name" use="required"/>
                <attribute name="origin" type="tns:Origin" use="optional"/>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Minerals-id">
        <restriction base="ID">
            <pattern value="([a-zA-Z]+\d{1,8})"/>
        </restriction>
    </simpleType>

    <simpleType name="Name">
        <restriction base="string">
            <pattern value="([a-zA-Z]+(\s[a-zA-Z]+)*)"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <pattern value="([a-zA-Z]+(\s[a-zA-Z]+)*)"/>
        </restriction>
    </simpleType>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="white"/>
            <enumeration value="black"/>
            <enumeration value="pink"/>
            <enumeration value="red"/>
            <enumeration value="blue"/>
            <enumeration value="green"/>
            <enumeration value="brown"/>
            <enumeration value="violet"/>
            <enumeration value="yellow"/>
            <enumeration value="motley"/>
        </restriction>
    </simpleType>

    <simpleType name="Edges-number">
        <restriction base="string">
            <pattern value="([4-9])|(1[0-4]{1})"/>
        </restriction>
    </simpleType>

    <simpleType name="Value">
        <restriction base="string">
            <pattern value="\d+\.\d+"/>
        </restriction>
    </simpleType>

    <simpleType name="Transparence">
        <restriction base="string">
            <enumeration value="true"/>
            <enumeration value="false"/>
        </restriction>
    </simpleType>

</schema>

=== alimdul/XMLWebParsing/src/main/resources/data/minerals.xml
<?xml version="1.0" encoding="UTF-8"?>
<minerals
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/minerals"
        xsi:schemaLocation="http://www.example.com/minerals minerals.xsd">

    <precious-stone minerals-id="PreciousStone1" name="Diamond">
        <color>pink</color>
        <transparence>true</transparence>
        <value>0.2</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone2" name="Diamond" origin="Canada">
        <color>yellow</color>
        <transparence>true</transparence>
        <value>0.25</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone3" name="Diamond" origin="Africa">
        <color>red</color>
        <transparence>true</transparence>
        <value>0.16</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone4" name="Corundum" origin="India">
        <color>red</color>
        <transparence>false</transparence>
        <value>0.25</value>
        <edges-number>10</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone5" name="Corundum" origin="India">
        <color>yellow</color>
        <transparence>true</transparence>
        <value>0.32</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone6" name="Spinel" origin="India">
        <color>white</color>
        <transparence>true</transparence>
        <value>0.32</value>
        <edges-number>8</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone7" name="Sapphire" origin="Australia">
        <color>blue</color>
        <transparence>true</transparence>
        <value>0.3</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone8" name="Sapphire" origin="USA">
        <color>blue</color>
        <transparence>false</transparence>
        <value>0.26</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone9" name="Dioptase" origin="Chile">
        <color>green</color>
        <transparence>false</transparence>
        <value>0.26</value>
        <edges-number>14</edges-number>
    </precious-stone>

    <precious-stone minerals-id="PreciousStone10" name="Dioptase" origin="USA">
        <color>blue</color>
        <transparence>false</transparence>
        <value>0.28</value>
        <edges-number>10</edges-number>
    </precious-stone>

    <semiprecious-stone minerals-id="SemipreciousStone1" name="Amethyst" origin="Ural">
        <color>violet</color>
        <transparence>true</transparence>
        <value>0.32</value>
        <edges-number>4</edges-number>
    </semiprecious-stone>

    <semiprecious-stone minerals-id="SemipreciousStone2" name="Amethyst" origin="Brazil">
        <color>red</color>
        <transparence>true</transparence>
        <value>0.34</value>
        <edges-number>8</edges-number>
    </semiprecious-stone>

    <semiprecious-stone minerals-id="SemipreciousStone3" name="Aquamarine" origin="Madagascar">
        <color>blue</color>
        <transparence>true</transparence>
        <value>0.4</value>
        <edges-number>8</edges-number>
    </semiprecious-stone>

    <semiprecious-stone minerals-id="SemipreciousStone4" name="Topaz" origin="Ural">
        <color>brown</color>
        <transparence>true</transparence>
        <value>0.28</value>
        <edges-number>12</edges-number>
    </semiprecious-stone>

    <semiprecious-stone minerals-id="SemipreciousStone5" name="Chrysolite" origin="USA">
        <color>green</color>
        <transparence>true</transparence>
        <value>0.22</value>
        <edges-number>14</edges-number>
    </semiprecious-stone>

    <semiprecious-stone minerals-id="SemipreciousStone6" name="Malachite">
        <color>green</color>
        <transparence>false</transparence>
        <value>0.44</value>
        <edges-number>4</edges-number>
    </semiprecious-stone>

</minerals>
